package com.base100.lex100.controller.entity.rubro;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.Rubro;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for Rubro List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("rubroList")
public class RubroList extends AbstractLogicalDeletionEntityList<Rubro>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private RubroSearch rubroSearch;
    @In(create=true)
    private RubroHome rubroHome;
    private static final String[] FILTERS = {
		"lower(rubro.codigo) like #{likePattern[rubroSearch.filter.codigo]}",
		"lower(rubro.descripcion) like #{likePattern[rubroSearch.filter.descripcion]}",
		"rubro.materia = #{rubroSearch.filter.materia}",
		"rubro.tipoInstancia = #{rubroSearch.filter.tipoInstancia}",

    };
	
    private static String[] byMateriaRestrictions ={
		"rubro.materia = #{materiaHome.isIdDefined() ? materiaHome.instance : null}"
    };
    
    public List<Rubro> getbyMateriaResultList(){
    	return getResultList(byMateriaRestrictions);
    }

    public List<Rubro> getbyMateriaAllResultList(){
    	return getAllResults(byMateriaRestrictions);
    }
    private static String[] byTipoInstanciaRestrictions ={
		"rubro.tipoInstancia = #{tipoInstanciaHome.isIdDefined() ? tipoInstanciaHome.instance : null}"
    };
    
    public List<Rubro> getbyTipoInstanciaResultList(){
    	return getResultList(byTipoInstanciaRestrictions);
    }

    public List<Rubro> getbyTipoInstanciaAllResultList(){
    	return getAllResults(byTipoInstanciaRestrictions);
    }

    @Override
    public String getEjbql() 
    { 
        return "select rubro from Rubro rubro";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<Rubro> getEntityHome() {
		return rubroHome;
	}

	public AbstractEntitySearch<Rubro> getEntitySearch() {
		return rubroSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (Rubro rubro, String page) {
		return super.doSelection(rubro, page);
	}

	public String doSelection (Rubro rubro, String page, String returnPage) {
		page = doSelection(rubro, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
