package com.base100.lex100.controller.entity.rubro;

import com.base100.expand.json.JSONException;
import com.base100.expand.json.JSONObject;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.EntityOperationException;
import com.base100.lex100.entity.Rubro;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.international.StatusMessage;

/**
 * Class for Rubro Home objects.
 * 
 * Generated by Expand.
 *
 */
@Name("rubroHome")
public class RubroHome extends AbstractEntityHome<Rubro>
{
    @In(create=true)
    private RubroSearch rubroSearch;

    /**
     * Set/change the entity being managed by id.
     * 
     * @param id new instance id
     */
    public void setRubroId(Integer id) {
        setId(id);
    }

    /**
     * Returns the current instance id.
     * 
     * @return the current id.
     */
    public Integer getRubroId() {
        return (Integer) getId();
    }

    
    public boolean isWired() {
        return true;
    }

    /**
     * Get the managed entity, or null if the id is not defined.
     * 
     * @return the managed entity, if any.
     */
    public Rubro getDefinedInstance() {
        return isIdDefined() ? getInstance() : null;
    }
 	

    @Override
	public String serializeId(Rubro rubro) {
		JSONObject jsonObject = new JSONObject();
		try {
			jsonObject.put("Id", rubro.getId());
		} catch (JSONException e) {
		}
		return jsonObject.toString(); 
	}

// Lookups

// Validation

// Operation event callbacks

	@Override
	public void afterSelect(){
	}

	@Override
	public void afterNew(Rubro rubro) {
        
        // settings of default values for properties can be inserted here

	}

	private boolean checkRequired() {
		boolean error = false;
		if (getInstance().getCodigo() == null) {
			error = true;
			addStatusMessage(StatusMessage.Severity.ERROR, "#{messages['rubro.codigo']} :" + org.jboss.seam.international.Messages.instance().get("error_notnull"));
		}
		if (getInstance().getDescripcion() == null) {
			error = true;
			addStatusMessage(StatusMessage.Severity.ERROR, "#{messages['rubro.descripcion']} :" + org.jboss.seam.international.Messages.instance().get("error_notnull"));
		}
		return error;
	}

	@Override
	public void beforeAdd(Rubro rubro) throws EntityOperationException {
		boolean error = false;
		if (rubroSearch.findByUuid(rubro.getUuid()) != null){
			error = true;
			addStatusMessage(StatusMessage.Severity.ERROR, org.jboss.seam.international.Messages.instance().get("error_duplicated_id") + " ("  + "UUID" + ")");
		}

		error |= checkRequired();
		if (error) {
			throw new EntityOperationException();
		}
	}
	
	@Override
	public void beforeUpdate(Rubro rubro) throws EntityOperationException {
		boolean error = false;
		error |= checkRequired();
		if (error) {
			throw new EntityOperationException();
		}
	}
	
	@Override
	public void beforeDelete(Rubro rubro) throws EntityOperationException {
	}

	@Override
	public void afterUpdate(Rubro rubro) throws EntityOperationException {
	}
	
	@Override
	public void afterAdd(Rubro rubro) throws EntityOperationException {
	}

	@Override
	public void afterDelete(Rubro rubro) throws EntityOperationException {
	}



}

