package com.base100.lex100.controller.entity.tipoBolillero;

import com.base100.expand.json.JSONException;
import com.base100.expand.json.JSONObject;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.EntityOperationException;
import com.base100.expand.seam.framework.entity.LookupEntitySelectionListener;
import com.base100.lex100.entity.TipoBolillero;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.international.StatusMessage;

/**
 * Class for TipoBolillero Home objects.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoBolilleroHome")
public class TipoBolilleroHome extends AbstractEntityHome<TipoBolillero>
{
    @In(create=true)
    private TipoBolilleroSearch tipoBolilleroSearch;

    /**
     * Set/change the entity being managed by id.
     * 
     * @param id new instance id
     */
    public void setTipoBolilleroId(Integer id) {
        setId(id);
    }

    /**
     * Returns the current instance id.
     * 
     * @return the current id.
     */
    public Integer getTipoBolilleroId() {
        return (Integer) getId();
    }

    
    public boolean isWired() {
        return true;
    }

    /**
     * Get the managed entity, or null if the id is not defined.
     * 
     * @return the managed entity, if any.
     */
    public TipoBolillero getDefinedInstance() {
        return isIdDefined() ? getInstance() : null;
    }
 	

    @Override
	public String serializeId(TipoBolillero tipoBolillero) {
		JSONObject jsonObject = new JSONObject();
		try {
			jsonObject.put("Id", tipoBolillero.getId());
		} catch (JSONException e) {
		}
		return jsonObject.toString(); 
	}

// Lookups

// Validation

// Operation event callbacks

	@Override
	public void afterSelect(){
	}

	@Override
	public void afterNew(TipoBolillero tipoBolillero) {
        
        // settings of default values for properties can be inserted here

	}

	private boolean checkRequired(TipoBolillero tipoBolillero) {
		boolean error = false;
		if (tipoBolillero.getCodigo() == null) {
			error = true;
			addStatusMessage(StatusMessage.Severity.ERROR, "#{messages['tipoBolillero.codigo']} :" + org.jboss.seam.international.Messages.instance().get("error_notnull"));
		}
		return error;
	}

	@Override
	public void beforeAdd(TipoBolillero tipoBolillero) throws EntityOperationException {
		boolean error = false;
		if (tipoBolilleroSearch.findByUuid(tipoBolillero.getUuid()) != null){
			error = true;
			addStatusMessage(StatusMessage.Severity.ERROR, org.jboss.seam.international.Messages.instance().get("error_duplicated_id") + " ("  + "UUID" + ")");
		}

		error |= checkRequired(tipoBolillero);
		if (error) {
			throw new EntityOperationException();
		}
	}
	
	@Override
	public void beforeUpdate(TipoBolillero tipoBolillero) throws EntityOperationException {
		boolean error = false;
		error |= checkRequired(tipoBolillero);
		if (error) {
			throw new EntityOperationException();
		}
	}
	
	@Override
	public void beforeDelete(TipoBolillero tipoBolillero) throws EntityOperationException {
	}

	@Override
	public void afterUpdate(TipoBolillero tipoBolillero) throws EntityOperationException {
	}
	
	@Override
	public void afterAdd(TipoBolillero tipoBolillero) throws EntityOperationException {
	}

	@Override
	public void afterDelete(TipoBolillero tipoBolillero) throws EntityOperationException {
	}


	/**
	 * TODO Auto-generated method stub
	 */
	public void lookupListMultiple(String returnPage) {
		initializeLookup(tipoBolilleroSearch, new LookupEntitySelectionListener<TipoBolillero>(returnPage, TipoBolillero.class, true) {
			public void updateLookup(TipoBolillero entity) {
				// TODO replace this code by the appropriate multiselection action code for each item..			
			}
			@Override
			public void finishSelection() {
				super.finishSelection();
				// TODO add the appropriate ending code.			
			}
		});
	}

}

