package com.base100.lex100.controller.entity.tipoBolillero;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TipoBolillero;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TipoBolillero List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoBolilleroList")
public class TipoBolilleroList extends AbstractLogicalDeletionEntityList<TipoBolillero>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TipoBolilleroSearch tipoBolilleroSearch;
    @In(create=true)
    private TipoBolilleroHome tipoBolilleroHome;
    private static final String[] FILTERS = {
		"lower(tipoBolillero.codigo) like #{likePattern[tipoBolilleroSearch.filter.codigo]}",
		"lower(tipoBolillero.descripcion) like #{likePattern[tipoBolilleroSearch.filter.descripcion]}",

    };
	

    @Override
    public String getEjbql() 
    { 
        return "select tipoBolillero from TipoBolillero tipoBolillero";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TipoBolillero> getEntityHome() {
		return tipoBolilleroHome;
	}

	public AbstractEntitySearch<TipoBolillero> getEntitySearch() {
		return tipoBolilleroSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TipoBolillero tipoBolillero, String page) {
		return super.doSelection(tipoBolillero, page);
	}

	public String doSelection (TipoBolillero tipoBolillero, String page, String returnPage) {
		page = doSelection(tipoBolillero, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
