package com.base100.lex100.controller.entity.tipoAsignacion;

import com.base100.lex100.entity.Materia;
import com.base100.lex100.entity.TipoAsignacion;
import com.base100.lex100.entity.TipoInstancia;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.intercept.BypassInterceptors;


import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TipoAsignacion search filters.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoAsignacionSearch")
@BypassInterceptors
public class TipoAsignacionSearch extends AbstractEntitySearch<TipoAsignacion>
{

	static public final String BY_UUID_STMT = 
		"FROM TipoAsignacion tipoAsignacion WHERE " +
	    "tipoAsignacion.uuid = :uuid";

	private String codigo;
	private String descripcion;
	private Materia materia;
	private TipoInstancia tipoInstancia;
	private String categoria;

	private TipoAsignacionSearch filter;

	public TipoAsignacionSearch() {
		setDefaultOrder("descripcion");
	}

	@Override
	public void clear() {
		this.codigo = null;
		this.descripcion = null;
		this.materia = null;
		this.tipoInstancia = null;
		this.categoria = null;
	}

	@Override
	public String getInitialPanelState()  {
		if (true
			&& this.codigo == null
			&& this.descripcion == null
			&& this.materia == null
			&& this.tipoInstancia == null
			&& this.categoria == null

	    ){
			return getPanelState();
		} else {
			return "open";
		}
	}

	@Override
	public boolean hasActiveSearch() {
		// TODO Auto-generated method stub
		return false;
	}


    public TipoAsignacion findByUuid(String uuid) {
    	return findByUuid (getEntityManager(), uuid); 
	}

    static public TipoAsignacion findByUuid(EntityManager entityManager, String tipoAsignacionUuid) {
		Query query = entityManager.createQuery(BY_UUID_STMT);
		TipoAsignacion tipoAsignacion = null;
		try {
			query.setParameter("uuid", tipoAsignacionUuid);
			tipoAsignacion = (TipoAsignacion)query.getSingleResult();
		} catch (Exception e) {
		}
		return tipoAsignacion;
	}

    /**
     * Returns the codigo search filter
     * 
     * @return	the codigo search filter
     */
    public String getCodigo() {
    	return codigo;
    }

    /**
     * Sets the codigo search filter
     * 
     * @param codigo the codigo search filter
     */
    public void setCodigo(String codigo) {
    	this.codigo = codigo;
    }
    
   /**
     * Clears the codigo search filter
     */
    public void clearCodigo() {
    	setCodigo(null);
    }

    /**
     * Returns the descripcion search filter
     * 
     * @return	the descripcion search filter
     */
    public String getDescripcion() {
    	return descripcion;
    }

    /**
     * Sets the descripcion search filter
     * 
     * @param descripcion the descripcion search filter
     */
    public void setDescripcion(String descripcion) {
    	this.descripcion = descripcion;
    }
    
   /**
     * Clears the descripcion search filter
     */
    public void clearDescripcion() {
    	setDescripcion(null);
    }

    /**
     * Returns the materia search filter
     * 
     * @return	the materia search filter
     */
    public Materia getMateria() {
    	return materia;
    }

    /**
     * Sets the materia search filter
     * 
     * @param materia the materia search filter
     */
    public void setMateria(Materia materia) {
    	this.materia = materia;
    }
    
   /**
     * Clears the materia search filter
     */
    public void clearMateria() {
    	setMateria(null);
    }

    /**
     * Returns the tipoInstancia search filter
     * 
     * @return	the tipoInstancia search filter
     */
    public TipoInstancia getTipoInstancia() {
    	return tipoInstancia;
    }

    /**
     * Sets the tipoInstancia search filter
     * 
     * @param tipoInstancia the tipoInstancia search filter
     */
    public void setTipoInstancia(TipoInstancia tipoInstancia) {
    	this.tipoInstancia = tipoInstancia;
    }
    
   /**
     * Clears the tipoInstancia search filter
     */
    public void clearTipoInstancia() {
    	setTipoInstancia(null);
    }

    /**
     * Returns the categoria search filter
     * 
     * @return	the categoria search filter
     */
    public String getCategoria() {
    	return categoria;
    }

    /**
     * Sets the categoria search filter
     * 
     * @param categoria the categoria search filter
     */
    public void setCategoria(String categoria) {
    	this.categoria = categoria;
    }
    
   /**
     * Clears the categoria search filter
     */
    public void clearCategoria() {
    	setCategoria(null);
    }



	public TipoAsignacionSearch getFilter() {
		if (filter == null) {
			filter = new TipoAsignacionSearch();
		}
		return filter;
	}

    @Override
    public void updateFilters() {
    	super.updateFilters();
		getFilter().setCodigo(getCodigo());
		getFilter().setDescripcion(getDescripcion());
		getFilter().setMateria(getMateria());
		getFilter().setTipoInstancia(getTipoInstancia());
		getFilter().setCategoria(getCategoria());
	}


}

