package com.base100.lex100.controller.entity.tipoAsignacion;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TipoAsignacion;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TipoAsignacion List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoAsignacionList")
public class TipoAsignacionList extends AbstractLogicalDeletionEntityList<TipoAsignacion>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TipoAsignacionSearch tipoAsignacionSearch;
    @In(create=true)
    private TipoAsignacionHome tipoAsignacionHome;
    private static final String[] FILTERS = {
		"lower(tipoAsignacion.codigo) like #{likePattern[tipoAsignacionSearch.filter.codigo]}",
		"lower(tipoAsignacion.descripcion) like #{likePattern[tipoAsignacionSearch.filter.descripcion]}",
		"tipoAsignacion.materia = #{tipoAsignacionSearch.filter.materia}",
		"tipoAsignacion.tipoInstancia = #{tipoAsignacionSearch.filter.tipoInstancia}",
		"lower(tipoAsignacion.categoria) like #{likePattern[tipoAsignacionSearch.filter.categoria]}",

    };
	
    private static String[] byMateriaRestrictions ={
		"tipoAsignacion.materia = #{materiaHome.isIdDefined() ? materiaHome.instance : null}"
    };
    
    public List<TipoAsignacion> getbyMateriaResultList(){
    	return getResultList(byMateriaRestrictions);
    }

    public List<TipoAsignacion> getbyMateriaAllResultList(){
    	return getAllResults(byMateriaRestrictions);
    }
    private static String[] byTipoInstanciaRestrictions ={
		"tipoAsignacion.tipoInstancia = #{tipoInstanciaHome.isIdDefined() ? tipoInstanciaHome.instance : null}"
    };
    
    public List<TipoAsignacion> getbyTipoInstanciaResultList(){
    	return getResultList(byTipoInstanciaRestrictions);
    }

    public List<TipoAsignacion> getbyTipoInstanciaAllResultList(){
    	return getAllResults(byTipoInstanciaRestrictions);
    }

    @Override
    public String getEjbql() 
    { 
        return "select tipoAsignacion from TipoAsignacion tipoAsignacion";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TipoAsignacion> getEntityHome() {
		return tipoAsignacionHome;
	}

	public AbstractEntitySearch<TipoAsignacion> getEntitySearch() {
		return tipoAsignacionSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TipoAsignacion tipoAsignacion, String page) {
		return super.doSelection(tipoAsignacion, page);
	}

	public String doSelection (TipoAsignacion tipoAsignacion, String page, String returnPage) {
		page = doSelection(tipoAsignacion, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
