package com.base100.lex100.controller.entity.turnoFiscaliaSala;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TurnoFiscaliaSala;
import com.base100.expand.seam.framework.entity.AbstractEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TurnoFiscaliaSala List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("turnoFiscaliaSalaList")
public class TurnoFiscaliaSalaList extends AbstractEntityList<TurnoFiscaliaSala>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TurnoFiscaliaSalaSearch turnoFiscaliaSalaSearch;
    @In(create=true)
    private TurnoFiscaliaSalaHome turnoFiscaliaSalaHome;
    private static final String[] FILTERS = {
		"turnoFiscaliaSala.camara = #{sessionState.globalCamara}",
		"turnoFiscaliaSala.competencia = #{turnoFiscaliaSalaSearch.filter.competencia}",
		"turnoFiscaliaSala.camara = #{turnoFiscaliaSalaSearch.filter.camara}",

    };
	
    private static String[] byCompetenciaRestrictions ={
		"turnoFiscaliaSala.competencia = #{competenciaHome.isIdDefined() ? competenciaHome.instance : null}"
    };
    
    public List<TurnoFiscaliaSala> getbyCompetenciaResultList(){
    	return getResultList(byCompetenciaRestrictions);
    }

    public List<TurnoFiscaliaSala> getbyCompetenciaAllResultList(){
    	return getAllResults(byCompetenciaRestrictions);
    }
    private static String[] byCamaraRestrictions ={
		"turnoFiscaliaSala.camara = #{camaraHome.isIdDefined() ? camaraHome.instance : null}"
    };
    
    public List<TurnoFiscaliaSala> getbyCamaraResultList(){
    	return getResultList(byCamaraRestrictions);
    }

    public List<TurnoFiscaliaSala> getbyCamaraAllResultList(){
    	return getAllResults(byCamaraRestrictions);
    }

    @Override
    public String getEjbql() 
    { 
        return "select turnoFiscaliaSala from TurnoFiscaliaSala turnoFiscaliaSala";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TurnoFiscaliaSala> getEntityHome() {
		return turnoFiscaliaSalaHome;
	}

	public AbstractEntitySearch<TurnoFiscaliaSala> getEntitySearch() {
		return turnoFiscaliaSalaSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TurnoFiscaliaSala turnoFiscaliaSala, String page) {
		return super.doSelection(turnoFiscaliaSala, page);
	}

	public String doSelection (TurnoFiscaliaSala turnoFiscaliaSala, String page, String returnPage) {
		page = doSelection(turnoFiscaliaSala, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
