package com.base100.lex100.mesaEntrada.asignacion;

public enum TipoSorteo {
	juzgado,
	sala,
	juzgadoPlenario,
	juzgadoSentencia,
	finJuzgadoSentencia,
	tribunalOral,
	salaCasacion,
	recursoQueja,
	recursoQuejaCasacion,
	fiscaliaJuzgado,
	fiscaliaTribunalOral,
	recursoLegajoEjecucion,
	recursoLegajoEjecucionCasacion,
	salaEstudio,
	salaRecursoExtraordinario,
	desafectacionSalaEstudio,
	cambioTipoCausa,
	incompetenciaExternaInformatizada,
	recuperacionIncompetencia,
	juzgadoMediacion,
	integracionSala,
	integracionSalaCasacion,
	integracionSalaEstudioCasacion,
	desestimacionIntegracionSala,
	desestimacionIntegracionSalaCasacion,
	vocalSalaEstudio,
	secretariaCorte,
	recursoQuejaCorte,
	recursoHonorariosCorte,
	recursoSaltoInstanciaCorte,
	recursoPresentacionesVarias,
	mediador,
	ordenCirculacionSala,
	perito,
	juzgadoEjecucion
}

