package com.base100.lex100.entity;
// Generated by Expand 4.0.0 

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.base100.expand.annotation.DataDefinition;
import com.base100.expand.annotation.EntityDefinition;
import com.base100.expand.annotation.EntityGroup;
import com.base100.expand.annotation.EntityIcon;
import com.base100.expand.annotation.GenerationProperty;
import com.base100.expand.annotation.Hidden;
import com.base100.expand.annotation.InteractiveModuleProperties;
import com.base100.expand.annotation.Lines;
import com.base100.expand.annotation.MultipleSelection;
import com.base100.expand.annotation.RestrictedEntity;
import com.base100.expand.annotation.index.IndexField;
import com.base100.lex100.component.audit.AbstractLogicalDeletion;
import com.base100.lex100.component.identity.IdentificableEntityListener;
import com.base100.lex100.manager.auditoria.IAuditableOperation;
import com.base100.lex100.manager.auditoria.OficinaSorteoEntityListener;

/**
 * OficinaSorteo generated by Expand 4.0.0
 */
@Entity
@EntityDefinition(label = "Oficina Sorteo", listLabel = "Oficina Sorteo")
@MultipleSelection
@EntityGroup("MesaEntrada")
@EntityIcon
@Lines(joinProperty="sorteo")
@RestrictedEntity
@InteractiveModuleProperties( {
		@GenerationProperty(propertyName = "gridColumns", propertyValue = "1") })
@Table(name = "OFICINA_SORTEO")
@EntityListeners({IdentificableEntityListener.class,OficinaSorteoEntityListener.class})
public class OficinaSorteo extends AbstractLogicalDeletion implements java.io.Serializable, IIdentificable, IAuditableOperation {

     private Integer id;
     private boolean turno;
     private int orden;
     private String uuid;
     private Oficina oficina;
     private Sorteo sorteo;
     private String auditableOperation;

    public OficinaSorteo() {
    }
	
    public OficinaSorteo(boolean turno, Oficina oficina, Sorteo sorteo, int orden) {
        this.turno = turno;
        this.oficina = oficina;
        this.sorteo = sorteo;
        this.orden = orden;
    }

    public OficinaSorteo(boolean turno, String uuid, Oficina oficina, Sorteo sorteo, int orden) {
       this.turno = turno;
       this.uuid = uuid;
       this.oficina = oficina;
       this.sorteo = sorteo;
       this.orden = orden;
    }

    @SequenceGenerator(name="generator", sequenceName="S_OFICINA_SORTEO", allocationSize=1)@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")    
	@DataDefinition(label = "Id Oficina Sorteo")
    @Column(name="ID_OFICINA_SORTEO", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
	@DataDefinition(label = "Turno")
    @Column(name="TURNO", nullable=false)
    public boolean isTurno() {
        return this.turno;
    }
    
    public void setTurno(boolean turno) {
        this.turno = turno;
    }
    
    @DataDefinition(label = "UUID",displayLength = 10,disabled = true)
	@IndexField
	@Hidden
    @Column(name="UUID", unique=true, length=40)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_OFICINA", nullable=false)
	@DataDefinition(label = "Oficina", filteredByGlobalSelection=false)
    public Oficina getOficina() {
        return this.oficina;
    }
    
    public void setOficina(Oficina oficina) {
        this.oficina = oficina;
    }
    
	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SORTEO", nullable=false)
    public Sorteo getSorteo() {
        return this.sorteo;
    }
    
    public void setSorteo(Sorteo sorteo) {
        this.sorteo = sorteo;
    }

	@DataDefinition(label = "Orden", defaultValue = "0")
    @Column(name="ORDEN", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
 
	@Transient
	public String getAuditableOperation() {
		return auditableOperation;
	}

	public void setAuditableOperation(String auditableOperation) {
		this.auditableOperation = auditableOperation;
	}
}


