package com.base100.lex100.controller.entity.turnoPolicia;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TurnoPolicia;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TurnoPolicia List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("turnoPoliciaList")
public class TurnoPoliciaList extends AbstractLogicalDeletionEntityList<TurnoPolicia>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TurnoPoliciaSearch turnoPoliciaSearch;
    @In(create=true)
    private TurnoPoliciaHome turnoPoliciaHome;
    private static final String[] FILTERS = {
		"turnoPolicia.oficina.camara = #{sessionState.globalCamara}",
		"turnoPolicia.desdeFecha >= #{turnoPoliciaSearch.filter.fromDesdeFecha}",
		"turnoPolicia.desdeFecha <= #{turnoPoliciaSearch.filter.toDesdeFecha}",
		"turnoPolicia.oficina = #{turnoPoliciaSearch.filter.oficina}",

    };
	
    private static String[] byOficinaRestrictions ={
		"turnoPolicia.oficina = #{oficinaHome.isIdDefined() ? oficinaHome.instance : null}"
    };
    
    public List<TurnoPolicia> getbyOficinaResultList(){
    	return getResultList(byOficinaRestrictions);
    }

    public List<TurnoPolicia> getbyOficinaAllResultList(){
    	return getAllResults(byOficinaRestrictions);
    }

    @SuppressWarnings("unchecked")
    public List<TurnoPolicia> getbyOficinaResultListWithNew(){
		List<TurnoPolicia> list = new ArrayList(getResultList(byOficinaRestrictions));
		list.add(getEntityHome().getEmptyInstance());
		return list;
	}

    @Override
    public String getEjbql() 
    { 
        return "select turnoPolicia from TurnoPolicia turnoPolicia";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TurnoPolicia> getEntityHome() {
		return turnoPoliciaHome;
	}

	public AbstractEntitySearch<TurnoPolicia> getEntitySearch() {
		return turnoPoliciaSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TurnoPolicia turnoPolicia, String page) {
		return super.doSelection(turnoPolicia, page);
	}

	public String doSelection (TurnoPolicia turnoPolicia, String page, String returnPage) {
		page = doSelection(turnoPolicia, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
