package com.base100.lex100.controller.entity.turnoFiscalia;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TurnoFiscalia;

/**
 * Class for TurnoFiscalia List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("turnoFiscaliaList")
public class TurnoFiscaliaList extends AbstractLogicalDeletionEntityList<TurnoFiscalia>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TurnoFiscaliaSearch turnoFiscaliaSearch;
    @In(create=true)
    private TurnoFiscaliaHome turnoFiscaliaHome;
    private static final String[] FILTERS = {
		"turnoFiscalia.oficina.camara = #{sessionState.globalCamara}",
		"turnoFiscalia.desdeFecha >= #{turnoFiscaliaSearch.filter.fromDesdeFecha}",
		"turnoFiscalia.desdeFecha <= #{turnoFiscaliaSearch.filter.toDesdeFecha}",
		"turnoFiscalia.fiscalia = #{turnoFiscaliaSearch.filter.fiscalia}",
		"turnoFiscalia.oficina = #{turnoFiscaliaSearch.filter.oficina}",
		"turnoFiscalia.tipoOficinaTurno = #{turnoFiscaliaSearch.filter.tipoOficinaTurno}",

    };
	
    private static String[] byOficinaRestrictions ={
		"turnoFiscalia.oficina = #{oficinaHome.isIdDefined() ? oficinaHome.instance : null}"
    };
    
    public List<TurnoFiscalia> getbyOficinaResultList(){
    	return getResultList(byOficinaRestrictions);
    }

    public List<TurnoFiscalia> getbyOficinaAllResultList(){
    	return getAllResults(byOficinaRestrictions);
    }

    @SuppressWarnings("unchecked")
    public List<TurnoFiscalia> getbyOficinaResultListWithNew(){
		List<TurnoFiscalia> list = new ArrayList(getResultList(byOficinaRestrictions));
		list.add(getEntityHome().getEmptyInstance());
		return list;
	}

    @Override
    public String getEjbql() 
    { 
        return "select turnoFiscalia from TurnoFiscalia turnoFiscalia";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TurnoFiscalia> getEntityHome() {
		return turnoFiscaliaHome;
	}

	public AbstractEntitySearch<TurnoFiscalia> getEntitySearch() {
		return turnoFiscaliaSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TurnoFiscalia turnoFiscalia, String page) {
		return super.doSelection(turnoFiscalia, page);
	}

	public String doSelection (TurnoFiscalia turnoFiscalia, String page, String returnPage) {
		page = doSelection(turnoFiscalia, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}


	public void doInitFilters(String tipoOficinaTurno) {
		turnoFiscaliaSearch.clear();
		turnoFiscaliaSearch.setToDesdeFecha(new Date());
		turnoFiscaliaSearch.setTipoOficinaTurno(tipoOficinaTurno);
		turnoFiscaliaSearch.setPanelState("open");
		turnoFiscaliaSearch.updateFilters();
		
		setFirstResult(null);
	}
}
