package com.base100.lex100.controller.entity.conexidadDeclarada;

import java.util.List;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;
import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.ConexidadDeclarada;

/**
 * Class for ConexidadDeclarada List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("conexidadDeclaradaList")
public class ConexidadDeclaradaList extends AbstractEntityList<ConexidadDeclarada>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private ConexidadDeclaradaSearch conexidadDeclaradaSearch;
    @In(create=true)
    private ConexidadDeclaradaHome conexidadDeclaradaHome;
    private static final String[] FILTERS = {
		"lower(conexidadDeclarada.descripcionOficina) like #{likePattern[conexidadDeclaradaSearch.filter.descripcionOficina]}",
		"conexidadDeclarada.oficina = #{conexidadDeclaradaSearch.filter.oficina}",

    };
	
    private static String[] byOficinaRestrictions ={
		"conexidadDeclarada.oficina = #{oficinaHome.isIdDefined() ? oficinaHome.instance : null}"
    };
    
    public List<ConexidadDeclarada> getbyOficinaResultList(){
    	return getResultList(byOficinaRestrictions);
    }

    public List<ConexidadDeclarada> getbyOficinaAllResultList(){
    	return getAllResults(byOficinaRestrictions);
    }

    @Override
    public String getEjbql() 
    { 
        return "select conexidadDeclarada from ConexidadDeclarada conexidadDeclarada";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<ConexidadDeclarada> getEntityHome() {
		return conexidadDeclaradaHome;
	}

	public AbstractEntitySearch<ConexidadDeclarada> getEntitySearch() {
		return conexidadDeclaradaSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (ConexidadDeclarada conexidadDeclarada, String page) {
		return super.doSelection(conexidadDeclarada, page);
	}

	public String doSelection (ConexidadDeclarada conexidadDeclarada, String page, String returnPage) {
		page = doSelection(conexidadDeclarada, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
