package com.base100.lex100.controller.entity.conexidadDeclarada;

import com.base100.expand.seam.framework.entity.AbstractEntitySearch;
import com.base100.lex100.entity.ConexidadDeclarada;
import com.base100.lex100.entity.Oficina;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.intercept.BypassInterceptors;



/**
 * Class for ConexidadDeclarada search filters.
 * 
 * Generated by Expand.
 *
 */
@Name("conexidadDeclaradaSearch")
@BypassInterceptors
public class ConexidadDeclaradaSearch extends AbstractEntitySearch<ConexidadDeclarada>
{


	private String descripcionOficina;
	private String uuid;
	private Oficina oficina;

	private ConexidadDeclaradaSearch filter;

	public ConexidadDeclaradaSearch() {
		setDefaultOrder("conexidadDeclarada.id");
	}

	@Override
	public void clear() {
		this.descripcionOficina = null;
		this.uuid = null;
		this.oficina = null;
	}

	@Override
	public String getInitialPanelState()  {
		if (true
			&& this.descripcionOficina == null
			&& this.uuid == null
			&& this.oficina == null

	    ){
			return getPanelState();
		} else {
			return "open";
		}
	}

	@Override
	public boolean hasActiveSearch() {
		// TODO Auto-generated method stub
		return false;
	}



    /**
     * Returns the descripcionOficina search filter
     * 
     * @return	the descripcionOficina search filter
     */
    public String getDescripcionOficina() {
    	return descripcionOficina;
    }

    /**
     * Sets the descripcionOficina search filter
     * 
     * @param descripcionOficina the descripcionOficina search filter
     */
    public void setDescripcionOficina(String descripcionOficina) {
    	this.descripcionOficina = descripcionOficina;
    }
    
   /**
     * Clears the descripcionOficina search filter
     */
    public void clearDescripcionOficina() {
    	setDescripcionOficina(null);
    }

    /**
     * Returns the uuid search filter
     * 
     * @return	the uuid search filter
     */
    public String getUuid() {
    	return uuid;
    }

    /**
     * Sets the uuid search filter
     * 
     * @param uuid the uuid search filter
     */
    public void setUuid(String uuid) {
    	this.uuid = uuid;
    }
    
   /**
     * Clears the uuid search filter
     */
    public void clearUuid() {
    	setUuid(null);
    }

    /**
     * Returns the oficina search filter
     * 
     * @return	the oficina search filter
     */
    public Oficina getOficina() {
    	return oficina;
    }

    /**
     * Sets the oficina search filter
     * 
     * @param oficina the oficina search filter
     */
    public void setOficina(Oficina oficina) {
    	this.oficina = oficina;
    }
    
   /**
     * Clears the oficina search filter
     */
    public void clearOficina() {
    	setOficina(null);
    }



	public ConexidadDeclaradaSearch getFilter() {
		if (filter == null) {
			filter = new ConexidadDeclaradaSearch();
		}
		return filter;
	}

    @Override
    public void updateFilters() {
		getFilter().setDescripcionOficina(getDescripcionOficina());
		getFilter().setUuid(getUuid());
		getFilter().setOficina(getOficina());
	}


}

