package com.base100.lex100.component.enumeration;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.international.Messages;

import com.base100.expand.seam.framework.component.enumeration.AbstractEnumeration;
import com.base100.expand.seam.framework.component.enumeration.ILabeledEnum;


/**
 * Enumeration.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoAsignacionLex100Enumeration")
@Scope(ScopeType.APPLICATION)
public class TipoAsignacionLex100Enumeration extends AbstractEnumeration {	
	public enum Type implements ILabeledEnum {
	
		migracion("tipoAsignacionLex100Enumeration.migracion", "0", null),
		turno("tipoAsignacionLex100Enumeration.turno", "1", null),
		sorteo("tipoAsignacionLex100Enumeration.sorteo", "2", null),
		oficinaUnica("tipoAsignacionLex100Enumeration.oficinaUnica", "3", null),
		conexidadAutomatica("tipoAsignacionLex100Enumeration.conexidadAutomatica", "4", null),
		conexidadDenunciada("tipoAsignacionLex100Enumeration.conexidadDenunciada", "5", null),
		conexidadFamilia("tipoAsignacionLex100Enumeration.conexidadFamilia", "6", null),
		conexidadSeleccionada("tipoAsignacionLex100Enumeration.conexidadSeleccionada", "7", null),
		radicacionPrevia("tipoAsignacionLex100Enumeration.radicacionPrevia", "8", null),
		anteriorAlSistema("tipoAsignacionLex100Enumeration.anteriorAlSistema", "9", null),
		ingresoDiferido("tipoAsignacionLex100Enumeration.ingresoDiferido", "10", null),
		manual("tipoAsignacionLex100Enumeration.manual", "11", null),
		copiaAlPrincipal("tipoAsignacionLex100Enumeration.copiaAlPrincipal", "12", null),
		copiaDesdePrincipal("tipoAsignacionLex100Enumeration.copiaDesdePrincipal", "13", null),
		provenienteMediacion("tipoAsignacionLex100Enumeration.provenienteMediacion", "14", null),
		calculada("tipoAsignacionLex100Enumeration.calculada", "15", null),
		integradaMigracion("tipoAsignacionLex100Enumeration.integradaMigracion", "16", null);
		
		private String label;
		private Object value;
		private String image;
		
		private Type(String label) {
			this.label = label;
			this.value = this;
		}

		private Type(String label, Object value) {
			this.label = label;
			this.value = value;
		}

		private Type(String label, Object value, String image) {
			this.label = label;
			this.value = value;
			this.image = image;
		}

		public String getLabel() {
			return label;
		}
	
		public Object getValue() {
			return value;
		}

		public String getImage() {
			return image;
		}
		
		public String getName() {
			return this.name();
		}
		
	}

	protected ILabeledEnum[] getEnumValues() {
		return Type.values();
	}

}

