package com.base100.lex100.component.enumeration;

import org.jboss.seam.Component;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.international.Messages;

import com.base100.expand.seam.framework.component.enumeration.AbstractEnumeration;
import com.base100.expand.seam.framework.component.enumeration.ILabeledEnum;
import com.base100.lex100.component.enumeration.TipoRadicacionEnumeration.Type;
import com.base100.lex100.entity.TipoInstancia;
import com.base100.lex100.entity.TipoOficina;


/**
 * Enumeration.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoRadicacionEnumeration")
@Scope(ScopeType.APPLICATION)
public class TipoRadicacionEnumeration extends AbstractEnumeration {	
	/**
	 * 
	 */
	private static final long serialVersionUID = -1401053870843699662L;

	public enum Type implements ILabeledEnum {
	
		juzgado("tipoRadicacion.juzgado", "J", 1, null),
		juzgadoPlenario("tipoRadicacion.juzgadoPlenario", "PL", 2, null),
		sala("tipoRadicacion.sala", "S", 3, null),
		tribunalOral("tipoRadicacion.tribunalOral", "TO", 4, null),
		salaCasacion("tipoRadicacion.salaCasacion", "SC", 5, null),
		juzgadoSentencia("tipoRadicacion.juzgadoSentencia", "JS", 6, null),	// SOLO PARA MIGRACION		
		salaEstudio("tipoRadicacion.salaEstudio", "SE", 7, null),	// Civiles
		//salaPronunciamientoSentencia("tipoRadicacion.salaPronunciamientoSentencia", "SI", 8, null),	// Civiles
		
		//salaRecursoExtraordinario("tipoRadicacion.salaRecursoExtraordinario", "SR", 9, null),	// Civiles OJO DEPRECATED
		
		//salaEstudioRecusacionConCausa("tipoRadicacion.salaEstudioRecusacionConCausa", "RC", 9, null),	// Civiles
		juzgadoMediacion("tipoRadicacion.juzgadoMediacion", "JM", 10, null), // Civiles. Juzgado donde se tramitó la mediación (para expedientes provenientes de mediacion)
		vocalias("tipoRadicacion.vocalia", "VO", 12, null), // Vocalias de Sala de apelaciones
		vocaliasCasacion("tipoRadicacion.vocaliaCasacion", "VC", 13, null), // Vocalias de sala de casación
		vocaliasEstudioCasacion("tipoRadicacion.vocaliaEstudioCasacion", "VE", 14, null), // Vocalias de estudio de sala de casación
		corteSuprema("tipoRadicacion.corteSuprema","CS",15, null),
		perito("tipoRadicacion.perito", "P", 16, null),		// Perito de la Seguridad Social
		juzgadoEjecucion("tipoRadicacion.juzgadoEjecucion", "JE", 17, null),		
		; 

		private String label;
		private Object value;
		private String image;
		private int orden;
		
		private Type(String label) {
			this.label = label;
			this.value = this;
		}

		private Type(String label, Object value) {
			this.label = label;
			this.value = value;
		}

		private Type(String label, Object value, int orden, String image) {
			this.label = label;
			this.value = value;
			this.image = image;
			this.orden = orden;
		}

		public String getLabel() {
			return label;
		}
	
		public Object getValue() {
			return value;
		}

		public String getImage() {
			return image;
		}
		
		public String getName() {
			return this.name();
		}

		public int getOrden() {
			return orden;
		}

		public void setOrden(int orden) {
			this.orden = orden;
		}
		
	}

	protected ILabeledEnum[] getEnumValues() {
		return Type.values();
	}

	public static boolean isCompatible(TipoOficina tipoOficina,	Type tipoRadicacion) {
		if (tipoOficina != null) {
			if (TipoRadicacionEnumeration.isAnyJuzgado(tipoRadicacion)) {
				return CodigoTipoOficinaEnumeration.isJuzgado(tipoOficina.getCodigo());
			} else if (TipoRadicacionEnumeration.isAnySala(tipoRadicacion) || TipoRadicacionEnumeration.isRadicacionSalaCasacion(tipoRadicacion) || TipoRadicacionEnumeration.isRadicacionCorteSuprema(tipoRadicacion)) {
				return CodigoTipoOficinaEnumeration.isSalaApelacion(tipoOficina.getCodigo());
			} else if (TipoRadicacionEnumeration.isRadicacionTribunalOral(tipoRadicacion)) {
				return CodigoTipoOficinaEnumeration.isTribunalOral(tipoOficina.getCodigo());
			}
		}
		return false;
	}
	
	public static boolean isAnyJuzgado(Type tipoRadicacion) { 
		if (Type.juzgado.equals(tipoRadicacion) || Type.juzgadoPlenario.equals(tipoRadicacion) || Type.juzgadoSentencia.equals(tipoRadicacion) || Type.juzgadoMediacion.equals(tipoRadicacion)) {
			return true;
		}
		return false;
	}
	
	public static boolean isRadicacionUsaOrdenCirculacion(String tipoRadicacion) { 
		if (Type.sala.getValue().equals(tipoRadicacion) ||
				Type.salaEstudio.getValue().equals(tipoRadicacion) ||
				Type.salaCasacion.getValue().equals(tipoRadicacion)) {
				
				return true;
			}
			return false;
		}
	
	public static boolean isAnySala(Type tipoRadicacion) { 
		if (Type.sala.equals(tipoRadicacion) ||
			Type.salaEstudio.equals(tipoRadicacion)) {
			
			return true;
		}
		return false;
	}
	
	public static boolean isAnySala(String tipoRadicacion) { 
		if (Type.sala.getValue().equals(tipoRadicacion) ||
			Type.salaEstudio.getValue().equals(tipoRadicacion)) {
			
			return true;
		}
		return false;
	}

	public static boolean isRadicacionSala(Type tipoRadicacion) {
		return Type.sala.equals(tipoRadicacion);
	}
	
	public static boolean isRadicacionSalaEstudio(Type tipoRadicacion) {
		return Type.salaEstudio.equals(tipoRadicacion);
	}

	public static boolean isRadicacionAnyVocalias(Type tipoRadicacion) {
		return isRadicacionVocalias(tipoRadicacion) || isRadicacionVocaliasCasacion(tipoRadicacion);
	}
	
	public static boolean isRadicacionVocalias(Type tipoRadicacion) {
		return Type.vocalias.equals(tipoRadicacion);
	}

	public static boolean isRadicacionVocalias(String tipoRadicacion) {
		return Type.vocalias.getValue().equals(tipoRadicacion);
	}

	public static boolean isRadicacionVocaliasCasacion(Type tipoRadicacion) {
		return Type.vocaliasCasacion.equals(tipoRadicacion);
	}

	public static boolean isRadicacionVocaliasCasacion(String tipoRadicacion) {
		return Type.vocaliasCasacion.getValue().equals(tipoRadicacion);
	}

	public static boolean isRadicacionVocaliasEstudioCasacion(Type tipoRadicacion) {
		return Type.vocaliasEstudioCasacion.equals(tipoRadicacion);
	}

	public static boolean isRadicacionVocaliasEstudioCasacion(String tipoRadicacion) {
		return Type.vocaliasEstudioCasacion.getValue().equals(tipoRadicacion);
	}
	
	public static boolean isRadicacionSalaCasacion(Type tipoRadicacion) {
		return Type.salaCasacion.equals(tipoRadicacion);
	}

	public static boolean isRadicacionSalaCasacion(String tipoRadicacion) {
		return Type.salaCasacion.getValue().equals(tipoRadicacion);
	}

	public static boolean isRadicacionCorteSuprema(Type tipoRadicacion) {
		return Type.corteSuprema.equals(tipoRadicacion);
	}

	public static boolean isRadicacionCorteSuprema(String tipoRadicacion) {
		return Type.corteSuprema.getValue().equals(tipoRadicacion);
	}
	
	public static boolean isRadicacionJuzgado(Type tipoRadicacion) {
		return Type.juzgado.equals(tipoRadicacion);
	}

	public static boolean isRadicacionJuzgado(String tipoRadicacion) {
		return Type.juzgado.getValue().equals(tipoRadicacion);
	}
	
	public static boolean isRadicacionSala(String tipoRadicacion) {
		return Type.sala.getValue().equals(tipoRadicacion);
	}
	

	public static boolean isRadicacionJuzgadoPlenario(Type tipoRadicacion) {
		return Type.juzgadoPlenario.equals(tipoRadicacion);
	}

	public static boolean isRadicacionJuzgadoSentencia(Type tipoRadicacion) {
		return Type.juzgadoSentencia.equals(tipoRadicacion);
	}

	public static boolean isRadicacionJuzgadoPlenario(String tipoRadicacion) {
		return Type.juzgadoPlenario.getValue().equals(tipoRadicacion);
	}

	public static boolean isRadicacionJuzgadoMediacion(Type tipoRadicacion) {
		return Type.juzgadoMediacion.equals(tipoRadicacion);
	}

	public static boolean isRadicacionJuzgadoMediacion(String tipoRadicacion) {
		return Type.juzgadoMediacion.getValue().equals(tipoRadicacion);
	}
	
	public static boolean isRadicacionJuzgadoEjecucion(String tipoRadicacion) {
		return Type.juzgadoEjecucion.getValue().equals(tipoRadicacion);
	}
		
	public static boolean isRadicacionTribunalOral(Type tipoRadicacion) {
		return Type.tribunalOral.equals(tipoRadicacion);
	}

	public static boolean isRadicacionPerito(String tipoRadicacion) {
		return Type.perito.getValue().equals(tipoRadicacion);
	}
	
	public String getLabelFor(String codigoRadicacion){
		String msg = getLabel(codigoRadicacion);
		if(msg != null){
			return Messages.instance().get(msg);
		}else{
			return "";
		}
	}
	
	public boolean isSala(Object value) {
		return (value != null) ? Type.sala.equals(getType(value)) : false;
	}

	public static Integer calculateCodigoTipoInstanciaByTipoRadicacion(TipoRadicacionEnumeration.Type tipoRadicacion) {
		if(TipoRadicacionEnumeration.Type.juzgado == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_PRIMERA_INSTANCIA;
		}
		if(TipoRadicacionEnumeration.Type.sala == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_APELACIONES;
		}
		if(TipoRadicacionEnumeration.Type.tribunalOral == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_TRIBUNAL_ORAL;
		}
		if(TipoRadicacionEnumeration.Type.salaCasacion == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_CASACION;
		}
		if(TipoRadicacionEnumeration.Type.corteSuprema == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_CORTESUPREMA;
		}
		if(TipoRadicacionEnumeration.Type.juzgadoPlenario == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_PRIMERA_INSTANCIA;
		}
		if(TipoRadicacionEnumeration.Type.juzgadoEjecucion == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_EJECUCION;
		}
		if(TipoRadicacionEnumeration.Type.vocalias == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_APELACIONES;
		}
		if(TipoRadicacionEnumeration.Type.vocaliasCasacion == tipoRadicacion || TipoRadicacionEnumeration.Type.vocaliasEstudioCasacion == tipoRadicacion){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_CASACION;
		}
		if(TipoRadicacionEnumeration.isAnyJuzgado(tipoRadicacion)){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_PRIMERA_INSTANCIA;
		}
		if(TipoRadicacionEnumeration.isAnySala(tipoRadicacion)){
			return TipoInstanciaEnumeration.TIPO_INSTANCIA_APELACIONES;
		}
		
		return null;
	}
	
	public static TipoRadicacionEnumeration.Type calculateTipoRadicacionByTipoInstancia(Integer codigoTipoInstancia) {
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_PRIMERA_INSTANCIA.equals(codigoTipoInstancia)){
			return TipoRadicacionEnumeration.Type.juzgado;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_APELACIONES.equals(codigoTipoInstancia)){
			return TipoRadicacionEnumeration.Type.sala;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_TRIBUNAL_ORAL.equals(codigoTipoInstancia)){
			return TipoRadicacionEnumeration.Type.tribunalOral;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_CASACION.equals(codigoTipoInstancia)){
			return TipoRadicacionEnumeration.Type.salaCasacion;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_CORTESUPREMA.equals(codigoTipoInstancia)){
			return TipoRadicacionEnumeration.Type.corteSuprema;
		}
		return null;
	}
	
	
	public static TipoRadicacionEnumeration.Type getTipoRadicacionByTipoInstancia(String abreviaturaTipoInstancia) {
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_PRIMERA_INSTANCIA_ABREVIATURA.equals(abreviaturaTipoInstancia)){
			return TipoRadicacionEnumeration.Type.juzgado;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_APELACIONES_ABREVIATURA.equals(abreviaturaTipoInstancia)){
			return TipoRadicacionEnumeration.Type.sala;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_TRIBUNAL_ORAL_ABREVIATURA.equals(abreviaturaTipoInstancia)){
			return TipoRadicacionEnumeration.Type.tribunalOral;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_CASACION_ABREVIATURA.equals(abreviaturaTipoInstancia)){
			return TipoRadicacionEnumeration.Type.salaCasacion;
		}
		if(TipoInstanciaEnumeration.TIPO_INSTANCIA_CORTESUPREMA_ABREVIATURA.equals(abreviaturaTipoInstancia)){
			return TipoRadicacionEnumeration.Type.corteSuprema;
		}
		
		
		return null;
		
		
		
		
		
	}
	
	

	
	
	public static TipoRadicacionEnumeration instance(){
		return (TipoRadicacionEnumeration) Component.getInstance(TipoRadicacionEnumeration.class, true);
	}

}

