package com.base100.lex100.component.enumeration;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.international.Messages;

import com.base100.expand.seam.framework.component.enumeration.AbstractEnumeration;
import com.base100.expand.seam.framework.component.enumeration.ILabeledEnum;

import java.lang.Integer;

/**
 * Enumeration.
 * 
 * Generated by Expand.
 *
 */
@Name("turnoSorteoEnumeration")
@Scope(ScopeType.APPLICATION)
public class TurnoSorteoEnumeration extends AbstractEnumeration {	
	public enum Type implements ILabeledEnum {
	
		sinTurno("turnoSorteoEnumeration.sinTurno", new Integer("0"), null),
		conTurnoManual("turnoSorteoEnumeration.conTurnoManual", new Integer("1"), null),
		conTurnoAutomatico("turnoSorteoEnumeration.conTurnoAutomatico", new Integer("2"), null),
		conTurnoContinuo("turnoSorteoEnumeration.conTurnoContinuo", new Integer("3"), null);

		private String label;
		private Object value;
		private String image;
		
		private Type(String label) {
			this.label = label;
			this.value = this;
		}

		private Type(String label, Object value) {
			this.label = label;
			this.value = value;
		}

		private Type(String label, Object value, String image) {
			this.label = label;
			this.value = value;
			this.image = image;
		}

		public String getLabel() {
			return label;
		}
	
		public Object getValue() {
			return value;
		}

		public String getImage() {
			return image;
		}
		
		public String getName() {
			return this.name();
		}
		
	}

	protected ILabeledEnum[] getEnumValues() {
		return Type.values();
	}
	
	public static boolean isSinTurno(Object value) {
		return Type.sinTurno.getValue().equals(value);
	}

	public static boolean isConTurnoManual(Object value) {
		return Type.conTurnoManual.getValue().equals(value);
	}

	public static boolean isConTurnoAutomatico(Object value) {
		return Type.conTurnoAutomatico.getValue().equals(value);
	}

	public static boolean isConTurnoContinuo(Object value) {
		return Type.conTurnoContinuo.getValue().equals(value);
	}
	
	public static boolean isConTurnoAnual(Object value) {
		return isConTurnoAutomatico(value) || isConTurnoContinuo(value);
		
	}
}

