package com.base100.lex100.controller.entity.tipoCambioAsignacion;

import java.util.List;
import java.util.ArrayList;

import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;

import com.base100.lex100.component.configuration.Configuration;
import com.base100.lex100.entity.TipoCambioAsignacion;
import com.base100.lex100.component.audit.AbstractLogicalDeletionEntityList;
import com.base100.expand.seam.framework.entity.AbstractEntityHome;
import com.base100.expand.seam.framework.entity.AbstractEntitySearch;

/**
 * Class for TipoCambioAsignacion List objects.
 * 
 * Generated by Expand.
 *
 */
@Name("tipoCambioAsignacionList")
public class TipoCambioAsignacionList extends AbstractLogicalDeletionEntityList<TipoCambioAsignacion>
{
	@In(create=true)
	private Configuration configuration;
    @In(create=true)
    private TipoCambioAsignacionSearch tipoCambioAsignacionSearch;
    @In(create=true)
    private TipoCambioAsignacionHome tipoCambioAsignacionHome;
    private static final String[] FILTERS = {
		"(tipoCambioAsignacion.materia is null or tipoCambioAsignacion.materia in (#{sessionState.globalMateriaSet}))",
		"lower(tipoCambioAsignacion.codigo) like #{likePattern[tipoCambioAsignacionSearch.filter.codigo]}",
		"lower(tipoCambioAsignacion.descripcion) like #{likePattern[tipoCambioAsignacionSearch.filter.descripcion]}",
		"tipoCambioAsignacion.tipoInstancia = #{tipoCambioAsignacionSearch.filter.tipoInstancia}",
		"tipoCambioAsignacion.materia = #{tipoCambioAsignacionSearch.filter.materia}",

    };
	
    private static String[] byTipoInstanciaRestrictions ={
		"tipoCambioAsignacion.tipoInstancia = #{tipoInstanciaHome.isIdDefined() ? tipoInstanciaHome.instance : null}"
    };
    
    public List<TipoCambioAsignacion> getbyTipoInstanciaResultList(){
    	return getResultList(byTipoInstanciaRestrictions);
    }

    public List<TipoCambioAsignacion> getbyTipoInstanciaAllResultList(){
    	return getAllResults(byTipoInstanciaRestrictions);
    }
    private static String[] byMateriaRestrictions ={
		"tipoCambioAsignacion.materia = #{materiaHome.isIdDefined() ? materiaHome.instance : null}"
    };
    
    public List<TipoCambioAsignacion> getbyMateriaResultList(){
    	return getResultList(byMateriaRestrictions);
    }

    public List<TipoCambioAsignacion> getbyMateriaAllResultList(){
    	return getAllResults(byMateriaRestrictions);
    }

    @Override
    public String getEjbql() 
    { 
        return "select tipoCambioAsignacion from TipoCambioAsignacion tipoCambioAsignacion";
    }

    @Override
    public String[] getFilters()
    {
        return FILTERS;
    }
    
    @Override
    public Integer getRowsPerPage()
    {
    	return configuration.getRowsPerPage();
    }
    
	public AbstractEntityHome<TipoCambioAsignacion> getEntityHome() {
		return tipoCambioAsignacionHome;
	}

	public AbstractEntitySearch<TipoCambioAsignacion> getEntitySearch() {
		return tipoCambioAsignacionSearch;
	}
	
	/* (non-Javadoc)
	 * @see com.base100.expand.seam.framework.entity.AbstractEntityList#doSelection(java.lang.Object, java.lang.String)
	 */
	public String doSelection (TipoCambioAsignacion tipoCambioAsignacion, String page) {
		return super.doSelection(tipoCambioAsignacion, page);
	}

	public String doSelection (TipoCambioAsignacion tipoCambioAsignacion, String page, String returnPage) {
		page = doSelection(tipoCambioAsignacion, page);
		if (returnPage != null) {
			getEntitySearch().setReturnPage(returnPage);
		}
		return page;
	}



}
